### PR TITLE
Renames WorkflowAction.nextState to state

### LINKED ISSUE #9: Rename Kotlin action nextState to state!
It's so confusing. Downside is bad effects on inline `action {}`s. That might be the upside as well.

### PR DESCRIPTION
**Pull request by rjrjr**
Undoing a crime against nature and common sense.

Closes #9

### CODE REVIEW

**Comment by rjrjr** [comment]
Oops, I was behind `main`. Updating…

**Comment by rjrjr** [comment]
@zach-klippenstein Any idea what that dokka failure means?

**Comment by zach-klippenstein** [comment]
```
e: /home/runner/work/workflow-kotlin/workflow-kotlin/workflow-runtime/src/test/java/com/squareup/workflow/RenderWorkflowInTest.kt: (377, 15): Unresolved reference: nextState
```

It looks like a compilation error, but I'm not sure why the assemble task didn't fail. Does it build locally?

**Comment by rjrjr** [comment]
```
gw clean build connectedCheck
```

Is there more to run these days?

**Comment by rjrjr** [comment]
Did find a lot of stale `nextState` in deprecation messages. Fixing…

**Comment by rjrjr** [comment]
But there is no `nextState` in the class it's complaining about. :/

**Comment by zach-klippenstein** [comment]
Yea, everything builds fine for me locally too, including `dokka`. Let's see if the rebuild passes I guess.

**Comment by rjrjr** [comment]
Found it, in workflow-runtime. Don't understand how top level build missed that.

**Comment by rjrjr** [comment]
Or a rebase weirdness? I don't know, tired, it works now.

**Comment by zach-klippenstein** [comment]
I must be tired too, still confused.

**Comment by forrestbice** [comment]
@rjrjr thanks for making this change! 🙌  Excited for this to make it to PoS

**Comment by Blisse** [comment]
Perhaps silly, but would've been happy to also see immutable val called `currentState` too.

**Pull request merged**
