### PR TITLE
Brings ViewStarter to the UI update.

### PR DESCRIPTION
**Pull request by rjrjr**
This is entirely a merge PR, except for the last commit. That one replicates the work from #602 , and should be reviewed please.

### CODE REVIEW

**Comment by rjrjr** [comment]
Having trouble seeing why the espresso tests are timing out. Not consistently happening at the same point, and they pass locally in a reasonable amount of time. Maybe infra? Rolling the dice again this morning.

**Comment by steve-the-edwards** [comment]
> Having trouble seeing why the espresso tests are timing out. Not consistently happening at the same point, and they pass locally in a reasonable amount of time. Maybe infra? Rolling the dice again this morning.

Reviewed last commit and looks good. Are you still waiting for green before taking this out of draft?

**Comment by rjrjr** [comment]
> > Having trouble seeing why the espresso tests are timing out. Not consistently happening at the same point, and they pass locally in a reasonable amount of time. Maybe infra? Rolling the dice again this morning.
> 
> Reviewed last commit and looks good. Are you still waiting for green before taking this out of draft?

Yes. Seems a lot more likely that I've broken something than that CI is actually being bad.

**Comment by rjrjr** [comment]
Cool cool cool, turned on [debugging](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) and now it's green.

**Review by steve-the-edwards — APPROVED** [review]
LGTM

**Pull request merged**
