### PR TITLE
661: Save JMH Benchmark Results

### LINKED ISSUE #661: Update JMH Benchmarks and ensure running/healthy
See https://workflow-community.slack.com/archives/CHTFPR277/p1575584077139800

### PR DESCRIPTION
**Pull request by steve-the-edwards**
Closes #661 .

Save results to a file (for now). Its not perfect, but its a least a historical record.

Also updated JMH version.

### CODE REVIEW

**Comment by steve-the-edwards** [comment]
CI Timeout on API 21 not concerning as typical flake unrelated to this.

**Review by rjrjr — APPROVED** [review]

**Comment by rjrjr** [comment]
> CI Timeout on API 21 not concerning as typical flake unrelated to this.

@steve-the-edwards @RBusarow is it time to delete this shard? I can't remember the last time it provided any signal that the other one didn't.

**Comment by RBusarow** [comment]
> > CI Timeout on API 21 not concerning as typical flake unrelated to this.
> 
> @steve-the-edwards @RBusarow is it time to delete this shard? I can't remember the last time it provided any signal that the other one didn't.

That depends on how much faith we have in the abstractions provided by Androidx, doesn't it?  Clearly there's some logic which is api-level sensitive, like that test I wrote which only fails on 31.

**Review by RBusarow — APPROVED** [review]

**Comment by rjrjr** [comment]
> > > CI Timeout on API 21 not concerning as typical flake unrelated to this.
> > 
> > 
> > @steve-the-edwards @RBusarow is it time to delete this shard? I can't remember the last time it provided any signal that the other one didn't.
> 
> That depends on how much faith we have in the abstractions provided by Androidx, doesn't it? Clearly there's some logic which is api-level sensitive, like that test I wrote which only fails on 31.

Sounds like we should replace it with an API 31 shard. Wonder if that's even possible.

**Pull request merged**
