### PR TITLE
update kotlin to 1.6.21

### PR DESCRIPTION
**Pull request by RBusarow**
- [x] run Square's internal CI against a snapshot (and pass)

### CODE REVIEW

**Review by rjrjr — APPROVED** [review]

**Review by steve-the-edwards — APPROVED** [review]
Nice!

**Comment by rjrjr** [comment]
@RBusarow Presuming it passes the internal suite, I'd like to get https://github.com/square/workflow-kotlin/pull/872 on its own before this, to minimize the swirl around the AlertDialog fix. Should be able to do that today. Is that going to get in your way?

**Comment by RBusarow** [comment]
> @RBusarow Presuming it passes the internal suite, I'd like to get #872 released on its own before this, to minimize the swirl around the AlertDialog fix. Should be able to do that today. Is that going to get in your way?

We have a handful of failing shards, but at first glance I don't think they're related to this update.  I won't be digging into that more until late today at the earliest, so I have no problem in holding back a bit. :)

**Comment by RBusarow** [comment]
@rjrjr @steve-the-edwards I've added a second commit to drop the "-Xfriend-paths=___" compiler argument for `:workflow-runtime`.  `WorkflowNode` was no longer accessible to `WorkflowNodeBenchmark` after the Kotlin update.  Instead, I'm using the shiny newish `workflowNodeCompilation.associateWith(main)`.

https://github.com/square/workflow-kotlin/pull/873/commits/1256b0ada35f92410dffe80aa8ee50578c24e1b9

**Pull request merged**
