### PR TITLE
Make ModalContainer provide individual SavedStateRegistries to each of its layers.

### LINKED ISSUE #469: Consider making ModalContainer wrap all its renderings with Named to differentiate layers

### LINKED ISSUE #470: Support nesting ModalContainers under BackStackContainers.
This currently doesn't work because `ModalContainer` doesn't set the `ViewTreeSavedStateRegistryOwner` on its modals, so if views in those modals ask for one, they'll get the wrong one or nothing. However, I think it would already be so weird to put a modal container inside a backstack that it's not worth putting the effort into wiring it up until we have a real use case.

Note that `WorkflowViewStub` has to solve the same problem, and it does so.

### PR DESCRIPTION
**Pull request by zach-klippenstein**
This fixes #469, and also fixes #470.

TODO:
- [x] Tests
- [ ] Test internally
- [ ] New test for the `only after super.onCreate` crash called out below.

### CODE REVIEW

**Review by steve-the-edwards — APPROVED** [review]

**Review by rjrjr — APPROVED** [review]
Very satisfying clean up in its own right, besides defusing those landmines.

**Comment by zach-klippenstein** [comment]
Testing internally [here](https://github.com/squareup/android-register/pull/53686).

**Comment by rjrjr** [comment]
A problem here is we're just moving the namespacing challenges around. As soon as we put a `ModalContainer` inside another `ModalContainer` of the same type and with no name or id, we get conflicts on the call to `stateRegistryAggregator.attachToParentRegistry` in `onAttachedToWindow`.

**Comment by rjrjr** [comment]
Still probably an improvement. Thinking.

**Comment by rjrjr** [comment]
Oh! Let's just build an optional `savedStateName: String? = null` into the existing `HasModals` interface.

**Comment by rjrjr** [comment]
That's kind of Android specific. And I actually already have similar use cases for container names around logging. Maybe:

```kotlin
interface ContainerRendering<W : Any>(
  val containerName: String = ""
}

interface HasModals<out B : Any, out M : Any> : ContainerRendering<B>

class BackStackScreen<StackedT: Any> : ContainerRendering<StackedT>
```

**Comment by rjrjr** [comment]
The `ContainerRendering` notion is not required for merging this, though. Probably another wild wrapping goose chase. 

I can hack together something on our internal uses in the meantime just to finish sanity checking this.

**Comment by rjrjr** [comment]
This sometimes fails when opening a modal. e.g., run the Tic Tac Toe sample, complete a game, and click Exit. I suspect it's masked in cases where the modal is shown immediately at launch.

```
E/TicTacToeComponent: java.lang.IllegalStateException: You can consumeRestoredStateForKey only after super.onCreate of corresponding component
        at androidx.savedstate.SavedStateRegistry.consumeRestoredStateForKey(SavedStateRegistry.java:77)
        at com.squareup.workflow1.ui.androidx.StateRegistryAggregator$lifecycleObserver$1.onStateChanged(StateRegistryAggregator.kt:89)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
        at com.squareup.workflow1.ui.androidx.StateRegistryAggregator.attachToParentRegistry(StateRegistryAggregator.kt:145)
        at com.squareup.workflow1.ui.backstack.ViewStateCache.attachToParentRegistry(ViewStateCache.kt:149)
        at com.squareup.workflow1.ui.backstack.BackStackContainer.onAttachedToWindow(BackStackContainer.kt:183)
        at android.view.View.dispatchAttachedToWindow(View.java:17381)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3319)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3326)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3326)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3326)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1658)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1386)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6733)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by rjrjr** [comment]
> Should try this same thing against main to see if the problem is specific to this PR.

Phew, main is fine.

**Comment by rjrjr** [comment]
I'm putting a pin in this. It's cleaner if we can get it to work, but the only thing it really accomplishes is fixing #470, which is a pretty contrived use case, and is tracked to remind us of this approach if we ever actually enounter it in the wild.

**Comment by rjrjr** [comment]
@helios175 and I have realized that we really do need this. As things stand, `BackStackContainer` is the only way to get a registry in place. That's lame.

**Comment by rjrjr** [comment]
> @helios175 and I have realized that we really do need this. As things stand, `BackStackContainer` is the only way to get a registry in place. That's lame.

Maybe? Or maybe we just forgot how to use `WorkflowLifecycleOwner`. Checking…

**Comment by rjrjr** [comment]
This branch is too stale, reproduced it in #656

**Pull request closed without merging**
